Vagrant.configure("2") do |config|
    config.vm.define "vm2" do |vm2|
      vm2.vm.box = "ubuntu/focal64"
      vm2.vm.network "private_network", type: "dhcp"
      
      vm2.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
      
      vm2.vm.provision "shell", path: "dhcp-client/setup.sh"
    end
  end
  