Vagrant.configure("2") do |config|
  config.vm.define "server" do |vm1|
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.network "private_network", type: "dhcp"
  
    vm1.vm.provision "shell", path: "./setup.sh"
    vm1.vm.provision "shell", path: "./services/dns/provision.sh"
    vm1.vm.provision "shell", path: "./services/web/provision.sh"
    vm1.vm.provision "shell", path: "./services/ftp/provision.sh"
    vm1.vm.provision "shell", path: "./services/nfs/provision.sh"
  end

  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/focal64"
    client.vm.network "private_network", type: "dhcp"

    client.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y dnsutils nfs-common
    SHELL
  end
end